spring.application.name=backend

server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
# spring.datasource.url=jdbc:postgresql://localhost:5432/inventorySales_db
# spring.datasource.username=postgres
# spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

spring.jackson.serialization.write-dates-as-timestamps=false

app.cors.allowed-origin=${APP_CORS_ALLOWED_ORIGIN:http://localhost:3000}

# cloudinary will failed when mvn clean install, because it needs value, must not empty
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}
# cloudinary.cloud-name=dm8tng6rp
# cloudinary.api-key=914516197863492
# cloudinary.api-secret=0dCKz5eubJM3KRBjhEm8RtHflbE

# AWS S3 document storage
aws.access-key-id=AWS_ACCESS_KEY_ID
aws.secret-access-key=AWS_SECRET_ACCESS_KEY
aws.s3.region=us-east-1
aws.s3.bucket=payroll-b-hr-1-2026

#for demo
#SPRING_DATASOURCE_URL=jdbc:jdbc:postgresql://dpg-abc123.internal:5432/inventory_db
#SPRING_DATASOURCE_USERNAME=inventory_db_user
#SPRING_DATASOURCE_PASSWORD=abcXYZ123